import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/layout/footer";
import { Cart } from "@/layout/cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Cart />
        {children}
        <Footer />
      </body>
    </html>
  );
}
