import type { Metadata } from "next";
import "@/app/globals.css";
import { Menu } from "@/layout/menu";
import { Marquee } from "@/components/marquee";
import { Cart } from "@/layout/cart";
import { Footer } from "@/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Cart />
      <Marquee
        text="BLACK FRIDAY PILGRIM 2025 - FRETE GRÁTIS ACIMA DE R$299 - 10X SEM JUROS"
        speed={20}
        repeat={3}
      />

      <Menu />
      {children}
      <Footer />
    </>
  );
}
